import { Card } from 'src/types/card.interface';

export const cards: Card[] = [
  // resource cards
  {
    id: 'lumber_yard_1',
    name: 'Lumber Yard',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['WOOD'] }],
  },
  {
    id: 'lumber_yard_2',
    name: 'Lumber Yard',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 4,
    provides: [{ type: 'resource', resources: ['WOOD'] }],
  },
  {
    id: 'stone_pit_1',
    name: 'Stone Pit',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['STONE'] }],
  },
  {
    id: 'stone_pit_2',
    name: 'Stone Pit',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 5,
    provides: [{ type: 'resource', resources: ['STONE'] }],
  },
  {
    id: 'clay_pool_1',
    name: 'Clay Pool',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['STONE'] }],
  },
  {
    id: 'clay_pool_2',
    name: 'Clay Pool',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 5,
    provides: [{ type: 'resource', resources: ['STONE'] }],
  },
  {
    id: 'orb_vein_1',
    name: 'Orb Vein',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['STONE'] }],
  },
  {
    id: 'orb_vein_2',
    name: 'Orb Vein',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 4,
    provides: [{ type: 'resource', resources: ['STONE'] }],
  },
  {
    id: 'clay_pit',
    name: 'Clay Pit',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['CLAY', 'ORE'] }],
  },
  {
    id: 'timber_yard',
    name: 'Timber Yard',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['STONE', 'WOOD'] }],
  },
  {
    id: 'excavation',
    name: 'Excavation',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 4,
    provides: [{ type: 'resource', resources: ['STONE', 'CLAY'] }],
  },
  {
    id: 'forest_cave',
    name: 'Forest Cave',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 5,
    provides: [{ type: 'resource', resources: ['ORE', 'WOOD'] }],
  },
  {
    id: 'mine',
    name: 'Mine',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['STONE', 'ORE'] }],
  },
  {
    id: 'tree_farm',
    name: 'Tree Farm',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['CLAY', 'WOOD'] }],
  },
  {
    id: 'sawmill',
    name: 'Sawmill',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['WOOD', 'WOOD'] }],
  },
  {
    id: 'sawmill',
    name: 'Sawmill',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['WOOD', 'WOOD'] }],
  },
  {
    id: 'quarry',
    name: 'Quarry',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['STONE', 'STONE'] }],
  },
  {
    id: 'quarry',
    name: 'Quarry',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['STONE', 'STONE'] }],
  },
  {
    id: 'brickyard',
    name: 'Brickyard',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['CLAY', 'CLAY'] }],
  },
  {
    id: 'brickyard',
    name: 'Brickyard',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['CLAY', 'CLAY'] }],
  },
  {
    id: 'foundry',
    name: 'Foundry',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['ORE', 'ORE'] }],
  },
  {
    id: 'foundry',
    name: 'Foundry',
    age: 1,
    type: 'RESOURCE',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['ORE', 'ORE'] }],
  },

  //   manufactured goods
  {
    id: 'loom',
    name: 'Loom',
    age: 1,
    type: 'MANUFACTURED',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['TEXTILE'] }],
  },
  {
    id: 'loom',
    name: 'Loom',
    age: 1,
    type: 'MANUFACTURED',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['TEXTILE'] }],
  },
  {
    id: 'loom',
    name: 'Loom',
    age: 2,
    type: 'MANUFACTURED',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['TEXTILE'] }],
  },
  {
    id: 'loom',
    name: 'Loom',
    age: 2,
    type: 'MANUFACTURED',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['TEXTILE'] }],
  },
  {
    id: 'press',
    name: 'Press',
    age: 1,
    type: 'MANUFACTURED',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['PAPER'] }],
  },
  {
    id: 'press',
    name: 'Press',
    age: 1,
    type: 'MANUFACTURED',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['PAPER'] }],
  },
  {
    id: 'press',
    name: 'Press',
    age: 2,
    type: 'MANUFACTURED',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['PAPER'] }],
  },
  {
    id: 'press',
    name: 'Press',
    age: 2,
    type: 'MANUFACTURED',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['PAPER'] }],
  },
  {
    id: 'glassworks',
    name: 'Glassworks',
    age: 1,
    type: 'MANUFACTURED',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['GLASS'] }],
  },
  {
    id: 'glassworks',
    name: 'Glassworks',
    age: 1,
    type: 'MANUFACTURED',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['GLASS'] }],
  },
  {
    id: 'glassworks',
    name: 'Glassworks',
    age: 2,
    type: 'MANUFACTURED',
    minPlayers: 3,
    provides: [{ type: 'resource', resources: ['GLASS'] }],
  },
  {
    id: 'glassworks',
    name: 'Glassworks',
    age: 2,
    type: 'MANUFACTURED',
    minPlayers: 6,
    provides: [{ type: 'resource', resources: ['GLASS'] }],
  },

  // civilian cards
  {
    id: 'pawnshop',
    name: 'Pawnshop',
    age: 1,
    type: 'CIVILIAN',
    minPlayers: 4,
    provides: [{ type: 'points', amount: 3 }],
  },
  {
    id: 'pawnshop',
    name: 'Pawnshop',
    age: 1,
    type: 'CIVILIAN',
    minPlayers: 7,
    provides: [{ type: 'points', amount: 3 }],
  },
  {
    id: 'baths',
    name: 'Baths',
    age: 1,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 3 }],
    chainTo: ['aqueduct'],
  },
  {
    id: 'baths',
    name: 'Baths',
    age: 1,
    type: 'CIVILIAN',
    minPlayers: 7,
    provides: [{ type: 'points', amount: 3 }],
    chainTo: ['aqueduct'],
  },
  {
    id: 'altar',
    name: 'Altar',
    age: 1,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 2 }],
    chainTo: ['temple'],
  },
  {
    id: 'altar',
    name: 'Altar',
    age: 1,
    type: 'CIVILIAN',
    minPlayers: 5,
    provides: [{ type: 'points', amount: 2 }],
    chainTo: ['temple'],
  },
  {
    id: 'theater',
    name: 'Theater',
    age: 1,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 2 }],
    chainTo: ['statue'],
  },
  {
    id: 'theater',
    name: 'Theater',
    age: 1,
    type: 'CIVILIAN',
    minPlayers: 6,
    provides: [{ type: 'points', amount: 2 }],
    chainTo: ['statue'],
  },
  {
    id: 'aqueduct',
    name: 'Aqueduct',
    age: 2,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 5 }],
    chainFrom: ['baths'],
  },
  {
    id: 'aqueduct',
    name: 'Aqueduct',
    age: 2,
    type: 'CIVILIAN',
    minPlayers: 7,
    provides: [{ type: 'points', amount: 5 }],
    chainFrom: ['baths'],
  },
  {
    id: 'temple',
    name: 'Temple',
    age: 2,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 3 }],
    chainFrom: ['altar'],
    chainTo: ['pantheon'],
  },
  {
    id: 'temple',
    name: 'Temple',
    age: 2,
    type: 'CIVILIAN',
    minPlayers: 7,
    provides: [{ type: 'points', amount: 3 }],
    chainFrom: ['altar'],
    chainTo: ['pantheon'],
  },
  {
    id: 'statue',
    name: 'Statue',
    age: 2,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 4 }],
    chainTo: ['gardens'],
    chainFrom: ['theater'],
  },
  {
    id: 'statue',
    name: 'Statue',
    age: 2,
    type: 'CIVILIAN',
    minPlayers: 7,
    provides: [{ type: 'points', amount: 4 }],
    chainTo: ['gardens'],
    chainFrom: ['theater'],
  },
  {
    id: 'patheon',
    name: 'Pantheon',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 7 }],
    chainFrom: ['temple'],
  },
  {
    id: 'patheon',
    name: 'Pantheon',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 6,
    provides: [{ type: 'points', amount: 7 }],
    chainFrom: ['temple'],
  },
  {
    id: 'gardens',
    name: 'Gardens',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 5 }],
    chainFrom: ['statue'],
  },
  {
    id: 'gardens',
    name: 'Gardens',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 4,
    provides: [{ type: 'points', amount: 5 }],
    chainFrom: ['statue'],
  },
  {
    id: 'town_hall',
    name: 'Town Hall',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 6 }],
    chainFrom: ['statue'],
  },
  {
    id: 'town_hall',
    name: 'Town Hall',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 5,
    provides: [{ type: 'points', amount: 6 }],
  },
  {
    id: 'town_hall',
    name: 'Town Hall',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 6,
    provides: [{ type: 'points', amount: 6 }],
  },
  {
    id: 'palace',
    name: 'Palace',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 3,
    provides: [{ type: 'points', amount: 8 }],
  },
  {
    id: 'palace',
    name: 'Palace',
    age: 3,
    type: 'CIVILIAN',
    minPlayers: 7,
    provides: [{ type: 'points', amount: 8 }],
  },

  // scientific cards
  {
    id: 'apothecary',
    name: 'Apothecary',
    age: 1,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['TEXTILE'] }],
    provides: [{ type: 'science', symbol: 'COMPASS' }],
    chainTo: ['stables', 'dispensary'],
  },
  {
    id: 'apothecary',
    name: 'Apothecary',
    age: 1,
    type: 'SCIENTIFIC',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['TEXTILE'] }],
    provides: [{ type: 'science', symbol: 'COMPASS' }],
    chainTo: ['stables', 'dispensary'],
  },
  {
    id: 'workshop',
    name: 'Workshop',
    age: 1,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['GLASS'] }],
    provides: [{ type: 'science', symbol: 'GEAR' }],
    chainTo: ['archery_range', 'laboratory'],
  },
  {
    id: 'workshop',
    name: 'Workshop',
    age: 1,
    type: 'SCIENTIFIC',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['GLASS'] }],
    provides: [{ type: 'science', symbol: 'GEAR' }],
    chainTo: ['archery_range', 'laboratory'],
  },
  {
    id: 'scriptorium',
    name: 'Scriptorium',
    age: 1,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['PAPER'] }],
    provides: [{ type: 'science', symbol: 'TABLET' }],
    chainTo: ['courthouse', 'library'],
  },
  {
    id: 'scriptorium',
    name: 'Scriptorium',
    age: 1,
    type: 'SCIENTIFIC',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['PAPER'] }],
    provides: [{ type: 'science', symbol: 'TABLET' }],
    chainTo: ['courthouse', 'library'],
  },
  {
    id: 'dispensary',
    name: 'Dispensary',
    age: 2,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['ORE', 'ORE', 'GLASS'] }],
    provides: [{ type: 'science', symbol: 'COMPASS' }],
    chainFrom: ['apothecary'],
    chainTo: ['arena', 'lodge'],
  },
  {
    id: 'dispensary',
    name: 'Dispensary',
    age: 2,
    type: 'SCIENTIFIC',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['ORE', 'ORE', 'GLASS'] }],
    provides: [{ type: 'science', symbol: 'COMPASS' }],
    chainFrom: ['apothecary'],
    chainTo: ['arena', 'lodge'],
  },
  {
    id: 'laboratory',
    name: 'Laboratory',
    age: 2,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['CLAY', 'CLAY', 'PAPER'] }],
    provides: [{ type: 'science', symbol: 'GEAR' }],
    chainFrom: ['workshop'],
    chainTo: ['siege_workshop', 'observatory'],
  },
  {
    id: 'laboratory',
    name: 'Laboratory',
    age: 2,
    type: 'SCIENTIFIC',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['CLAY', 'CLAY', 'PAPER'] }],
    provides: [{ type: 'science', symbol: 'GEAR' }],
    chainFrom: ['workshop'],
    chainTo: ['siege_workshop', 'observatory'],
  },
  {
    id: 'library',
    name: 'Library',
    age: 2,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['STONE', 'STONE', 'TEXTILE'] }],
    provides: [{ type: 'science', symbol: 'TABLET' }],
    chainFrom: ['scriptorium'],
    chainTo: ['senate', 'university'],
  },
  {
    id: 'library',
    name: 'Library',
    age: 2,
    type: 'SCIENTIFIC',
    minPlayers: 6,
    cost: [{ type: 'resource', resources: ['STONE', 'STONE', 'TEXTILE'] }],
    provides: [{ type: 'science', symbol: 'TABLET' }],
    chainFrom: ['scriptorium'],
    chainTo: ['senate', 'university'],
  },
  {
    id: 'school',
    name: 'School',
    age: 2,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['WOOD', 'PAPER'] }],
    provides: [{ type: 'science', symbol: 'TABLET' }],
    chainTo: ['academy', 'study'],
  },
  {
    id: 'school',
    name: 'School',
    age: 2,
    type: 'SCIENTIFIC',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['WOOD', 'PAPER'] }],
    provides: [{ type: 'science', symbol: 'TABLET' }],
    chainTo: ['academy', 'study'],
  },
  {
    id: 'lodge',
    name: 'Lodge',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [
      { type: 'resource', resources: ['CLAY', 'CLAY', 'PAPER', 'TEXTILE'] },
    ],
    provides: [{ type: 'science', symbol: 'COMPASS' }],
    chainFrom: ['dispensary'],
  },
  {
    id: 'lodge',
    name: 'Lodge',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 6,
    cost: [
      { type: 'resource', resources: ['CLAY', 'CLAY', 'PAPER', 'TEXTILE'] },
    ],
    provides: [{ type: 'science', symbol: 'COMPASS' }],
    chainFrom: ['dispensary'],
  },
  {
    id: 'observatory',
    name: 'Observatory',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['ORE', 'ORE', 'GLASS', 'TEXTILE'] }],
    provides: [{ type: 'science', symbol: 'GEAR' }],
    chainFrom: ['laboratory'],
  },
  {
    id: 'observatory',
    name: 'Observatory',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['ORE', 'ORE', 'GLASS', 'TEXTILE'] }],
    provides: [{ type: 'science', symbol: 'GEAR' }],
    chainFrom: ['laboratory'],
  },
  {
    id: 'university',
    name: 'University',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['WOOD', 'WOOD', 'PAPER', 'GLASS'] }],
    provides: [{ type: 'science', symbol: 'TABLET' }],
    chainFrom: ['library'],
  },
  {
    id: 'university',
    name: 'University',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['WOOD', 'WOOD', 'PAPER', 'GLASS'] }],
    provides: [{ type: 'science', symbol: 'TABLET' }],
    chainFrom: ['library'],
  },
  {
    id: 'academy',
    name: 'Academy',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [
      { type: 'resource', resources: ['STONE', 'STONE', 'STONE', 'GLASS'] },
    ],
    provides: [{ type: 'science', symbol: 'COMPASS' }],
    chainFrom: ['school'],
  },
  {
    id: 'academy',
    name: 'Academy',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 7,
    cost: [
      { type: 'resource', resources: ['STONE', 'STONE', 'STONE', 'GLASS'] },
    ],
    provides: [{ type: 'science', symbol: 'COMPASS' }],
    chainFrom: ['school'],
  },
  {
    id: 'study',
    name: 'Study',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['WOOD', 'PAPER', 'TEXTILE'] }],
    provides: [{ type: 'science', symbol: 'GEAR' }],
    chainFrom: ['school'],
  },
  {
    id: 'study',
    name: 'Study',
    age: 3,
    type: 'SCIENTIFIC',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['WOOD', 'PAPER', 'TEXTILE'] }],
    provides: [{ type: 'science', symbol: 'GEAR' }],
    chainFrom: ['school'],
  },

  // military cards
  {
    id: 'stockade',
    name: 'Stockade',
    age: 1,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['WOOD'] }],
    provides: [{ type: 'military', strength: 1 }],
  },
  {
    id: 'stockade',
    name: 'Stockade',
    age: 1,
    type: 'MILITARY',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['WOOD'] }],
    provides: [{ type: 'military', strength: 1 }],
  },
  {
    id: 'barracks',
    name: 'Barracks',
    age: 1,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['ORE'] }],
    provides: [{ type: 'military', strength: 1 }],
  },
  {
    id: 'barracks',
    name: 'Barracks',
    age: 1,
    type: 'MILITARY',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['ORE'] }],
    provides: [{ type: 'military', strength: 1 }],
  },
  {
    id: 'guard_tower',
    name: 'Guard Tower',
    age: 1,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['CLAY'] }],
    provides: [{ type: 'military', strength: 1 }],
  },
  {
    id: 'guard_tower',
    name: 'Guard Tower',
    age: 1,
    type: 'MILITARY',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['CLAY'] }],
    provides: [{ type: 'military', strength: 1 }],
  },
  {
    id: 'walls',
    name: 'Walls',
    age: 2,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['STONE', 'STONE', 'STONE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainTo: ['fortifications'],
  },
  {
    id: 'walls',
    name: 'Walls',
    age: 2,
    type: 'MILITARY',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['STONE', 'STONE', 'STONE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainTo: ['fortifications'],
  },
  {
    id: 'training_ground',
    name: 'Training Ground',
    age: 2,
    type: 'MILITARY',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['WOOD', 'ORE', 'ORE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainTo: ['circus'],
  },
  {
    id: 'training_ground',
    name: 'Training Ground',
    age: 2,
    type: 'MILITARY',
    minPlayers: 6,
    cost: [{ type: 'resource', resources: ['WOOD', 'ORE', 'ORE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainTo: ['circus'],
  },
  {
    id: 'training_ground',
    name: 'Training Ground',
    age: 2,
    type: 'MILITARY',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['WOOD', 'ORE', 'ORE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainTo: ['circus'],
  },
  {
    id: 'stables',
    name: 'Stables',
    age: 2,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['WOOD', 'CLAY', 'ORE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainFrom: ['apothecary'],
  },
  {
    id: 'stables',
    name: 'Stables',
    age: 2,
    type: 'MILITARY',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['WOOD', 'CLAY', 'ORE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainFrom: ['apothecary'],
  },
  {
    id: 'archery_range',
    name: 'Archery Range',
    age: 2,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['WOOD', 'WOOD', 'ORE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainFrom: ['workshop'],
  },
  {
    id: 'archery_range',
    name: 'Archery Range',
    age: 2,
    type: 'MILITARY',
    minPlayers: 6,
    cost: [{ type: 'resource', resources: ['WOOD', 'WOOD', 'ORE'] }],
    provides: [{ type: 'military', strength: 2 }],
    chainFrom: ['workshop'],
  },
  {
    id: 'fortifications',
    name: 'Foritfications',
    age: 3,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['STONE', 'ORE', 'ORE', 'ORE'] }],
    provides: [{ type: 'military', strength: 3 }],
    chainFrom: ['walls'],
  },
  {
    id: 'fortifications',
    name: 'Foritfications',
    age: 3,
    type: 'MILITARY',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['STONE', 'ORE', 'ORE', 'ORE'] }],
    provides: [{ type: 'military', strength: 3 }],
    chainFrom: ['walls'],
  },
  {
    id: 'circus',
    name: 'Circus',
    age: 3,
    type: 'MILITARY',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['STONE', 'STONE', 'STONE', 'ORE'] }],
    provides: [{ type: 'military', strength: 3 }],
    chainFrom: ['traning_ground'],
  },
  {
    id: 'circus',
    name: 'Circus',
    age: 3,
    type: 'MILITARY',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['STONE', 'STONE', 'STONE', 'ORE'] }],
    provides: [{ type: 'military', strength: 3 }],
    chainFrom: ['traning_ground'],
  },
  {
    id: 'circus',
    name: 'Circus',
    age: 3,
    type: 'MILITARY',
    minPlayers: 6,
    cost: [{ type: 'resource', resources: ['STONE', 'STONE', 'STONE', 'ORE'] }],
    provides: [{ type: 'military', strength: 3 }],
    chainFrom: ['traning_ground'],
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    age: 3,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['ORE', 'WOOD', 'WOOD', 'TEXTILE'] }],
    provides: [{ type: 'military', strength: 3 }],
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    age: 3,
    type: 'MILITARY',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['ORE', 'WOOD', 'WOOD', 'TEXTILE'] }],
    provides: [{ type: 'military', strength: 3 }],
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    age: 3,
    type: 'MILITARY',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['ORE', 'WOOD', 'WOOD', 'TEXTILE'] }],
    provides: [{ type: 'military', strength: 3 }],
  },
  {
    id: 'siege_workshop',
    name: 'Siege Workshop',
    age: 3,
    type: 'MILITARY',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['WOOD', 'CLAY', 'CLAY', 'CLAY'] }],
    provides: [{ type: 'military', strength: 3 }],
  },
  {
    id: 'siege_workshop',
    name: 'Siege Workshop',
    age: 3,
    type: 'MILITARY',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['WOOD', 'CLAY', 'CLAY', 'CLAY'] }],
    provides: [{ type: 'military', strength: 3 }],
  },

  //   commercial cards
  {
    id: 'tavern',
    name: 'Tavern',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 4,
    provides: [{ type: 'coins', amount: 5 }],
  },
  {
    id: 'tavern',
    name: 'Tavern',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 5,
    provides: [{ type: 'coins', amount: 5 }],
  },
  {
    id: 'tavern',
    name: 'Tavern',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 7,
    provides: [{ type: 'coins', amount: 5 }],
  },
  {
    id: 'east_trading_post',
    name: 'East Trading Post',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 3,
    provides: [
      {
        type: 'discount',
        neighbors: 'right',
        resources: ['CLAY', 'ORE', 'STONE', 'WOOD'],
      },
    ],
    chainTo: ['forum'],
  },
  {
    id: 'east_trading_post',
    name: 'East Trading Post',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 7,
    provides: [
      {
        type: 'discount',
        neighbors: 'right',
        resources: ['CLAY', 'ORE', 'STONE', 'WOOD'],
      },
    ],
    chainTo: ['forum'],
  },
  {
    id: 'west_trading_post',
    name: 'West Trading Post',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 3,
    provides: [
      {
        type: 'discount',
        neighbors: 'left',
        resources: ['CLAY', 'ORE', 'STONE', 'WOOD'],
      },
    ],
    chainTo: ['forum'],
  },
  {
    id: 'west_trading_post',
    name: 'West Trading Post',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 7,
    provides: [
      {
        type: 'discount',
        neighbors: 'left',
        resources: ['CLAY', 'ORE', 'STONE', 'WOOD'],
      },
    ],
    chainTo: ['forum'],
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 3,
    provides: [
      {
        type: 'discount',
        neighbors: 'both',
        resources: ['GLASS', 'PAPER', 'TEXTILE'],
      },
    ],
    chainTo: ['caravansery'],
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    age: 1,
    type: 'COMMERCIAL',
    minPlayers: 6,
    provides: [
      {
        type: 'discount',
        neighbors: 'both',
        resources: ['GLASS', 'PAPER', 'TEXTILE'],
      },
    ],
    chainTo: ['caravansery'],
  },
  {
    id: 'forum',
    name: 'Forum',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['CLAY', 'CLAY'] }],
    provides: [{ type: 'resource-choice', resources: ['GLASS', 'TEXTILE', 'PAPER'] }],
    chainFrom: ['east_trading_post', 'west_trading_post'],
    chainTo: ['haven'],
  },
  {
    id: 'forum',
    name: 'Forum',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 6,
    cost: [{ type: 'resource', resources: ['CLAY', 'CLAY'] }],
    provides: [{ type: 'resource-choice', resources: ['GLASS', 'TEXTILE', 'PAPER'] }],
    chainFrom: ['east_trading_post', 'west_trading_post'],
    chainTo: ['haven'],
  },
  {
    id: 'forum',
    name: 'Forum',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['CLAY', 'CLAY'] }],
    provides: [{ type: 'resource-choice', resources: ['GLASS', 'TEXTILE', 'PAPER'] }],
    chainFrom: ['east_trading_post', 'west_trading_post'],
    chainTo: ['haven'],
  },
  {
    id: 'caravansery',
    name: 'Caravansery',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['WOOD', 'WOOD'] }],
    provides: [{ type: 'resource-choice', resources: ['WOOD', 'CLAY', 'ORE', 'STONE'] }],
    chainFrom: ['marketplace'],
    chainTo: ['lighthouse'],
  },
  {
    id: 'caravansery',
    name: 'Caravansery',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['WOOD', 'WOOD'] }],
    provides: [{ type: 'resource-choice', resources: ['WOOD', 'CLAY', 'ORE', 'STONE'] }],
    chainFrom: ['marketplace'],
    chainTo: ['lighthouse'],
  },
  {
    id: 'caravansery',
    name: 'Caravansery',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 6,
    cost: [{ type: 'resource', resources: ['WOOD', 'WOOD'] }],
    provides: [{ type: 'resource-choice', resources: ['WOOD', 'CLAY', 'ORE', 'STONE'] }],
    chainFrom: ['marketplace'],
    chainTo: ['lighthouse'],
  },
  {
    id: 'vineyard',
    name: 'Vineyard',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 3,
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'RESOURCE',
        coinPerCard: 1,
        from: 'both',
      },
    ],
  },
  {
    id: 'vineyard',
    name: 'Vineyard',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 6,
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'RESOURCE',
        coinPerCard: 1,
        from: 'both',
      },
    ],
  },
  {
    id: 'bazar',
    name: 'Bazar',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 4,
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'MANUFACTURED',
        coinPerCard: 2,
        from: 'both',
      },
    ],
  },
  {
    id: 'bazar',
    name: 'Bazar',
    age: 2,
    type: 'COMMERCIAL',
    minPlayers: 7,
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'MANUFACTURED',
        coinPerCard: 2,
        from: 'both',
      },
    ],
  },
  {
    id: 'arena',
    name: 'Arena',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['ORE', 'STONE', 'STONE'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'WONDER',
        coinPerCard: 3,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'WONDER',
        pointPerCard: 1,
        from: 'self',
      },
    ],
    chainFrom: ['dispensary'],
  },
  {
    id: 'arena',
    name: 'Arena',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 5,
    cost: [{ type: 'resource', resources: ['ORE', 'STONE', 'STONE'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'WONDER',
        coinPerCard: 3,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'WONDER',
        pointPerCard: 1,
        from: 'self',
      },
    ],
    chainFrom: ['dispensary'],
  },
  {
    id: 'arena',
    name: 'Arena',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 7,
    cost: [{ type: 'resource', resources: ['ORE', 'STONE', 'STONE'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'WONDER',
        coinPerCard: 3,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'WONDER',
        pointPerCard: 1,
        from: 'self',
      },
    ],
    chainFrom: ['dispensary'],
  },
  {
    id: 'haven',
    name: 'Haven',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['TEXTILE', 'ORE', 'WOOD'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'RESOURCE',
        coinPerCard: 1,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'RESOURCE',
        pointPerCard: 1,
        from: 'self',
      },
    ],
    chainFrom: ['forum'],
  },
  {
    id: 'haven',
    name: 'Haven',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['TEXTILE', 'ORE', 'WOOD'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'RESOURCE',
        coinPerCard: 1,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'RESOURCE',
        pointPerCard: 1,
        from: 'self',
      },
    ],
    chainFrom: ['forum'],
  },
  {
    id: 'lighthouse',
    name: 'Lighthouse',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['STONE', 'GLASS'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'COMMERCIAL',
        coinPerCard: 1,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'COMMERCIAL',
        pointPerCard: 1,
        from: 'self',
      },
    ],
    chainFrom: ['caravansery'],
  },
  {
    id: 'lighthouse',
    name: 'Lighthouse',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 6,
    cost: [{ type: 'resource', resources: ['STONE', 'GLASS'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'COMMERCIAL',
        coinPerCard: 1,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'COMMERCIAL',
        pointPerCard: 1,
        from: 'self',
      },
    ],
    chainFrom: ['caravansery'],
  },
  {
    id: 'chamber_of_commerce',
    name: 'Chamber of Commerce',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 4,
    cost: [{ type: 'resource', resources: ['CLAY', 'CLAY', 'PAPER'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'MANUFACTURED',
        coinPerCard: 2,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'MANUFACTURED',
        pointPerCard: 2,
        from: 'self',
      },
    ],
  },
  {
    id: 'chamber_of_commerce',
    name: 'Chamber of Commerce',
    age: 3,
    type: 'COMMERCIAL',
    minPlayers: 6,
    cost: [{ type: 'resource', resources: ['CLAY', 'CLAY', 'PAPER'] }],
    provides: [
      {
        type: 'coin-per-card',
        perCardType: 'MANUFACTURED',
        coinPerCard: 2,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'MANUFACTURED',
        pointPerCard: 2,
        from: 'self',
      },
    ],
  },

  //   guild cards
  {
    id: 'workers_guild',
    name: 'Workers Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [
      { type: 'resource', resources: ['ORE', 'ORE', 'CLAY', 'STONE', 'WOOD'] },
    ],
    provides: [
      {
        type: 'point-per-card',
        perCardType: 'RESOURCE',
        pointPerCard: 1,
        from: 'neighbors',
      },
    ],
  },
  {
    id: 'craftsmens_guild',
    name: 'Craftsmens Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['ORE', 'ORE', 'STONE', 'STONE'] }],
    provides: [
      {
        type: 'point-per-card',
        perCardType: 'MANUFACTURED',
        pointPerCard: 2,
        from: 'neighbors',
      },
    ],
  },
  {
    id: 'shipowners_guild',
    name: 'Shipowners Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [
      {
        type: 'resource',
        resources: ['WOOD', 'WOOD', 'WOOD', 'PAPER', 'GLASS'],
      },
    ],
    provides: [
      {
        type: 'point-per-card',
        perCardType: 'RESOURCE',
        pointPerCard: 1,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'MANUFACTURED',
        pointPerCard: 1,
        from: 'self',
      },
      {
        type: 'point-per-card',
        perCardType: 'GUILD',
        pointPerCard: 1,
        from: 'self',
      },
    ],
  },
  {
    id: 'traders_guild',
    name: 'Traders Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [{ type: 'resource', resources: ['TEXTILE', 'PAPER', 'GLASS'] }],
    provides: [
      {
        type: 'point-per-card',
        perCardType: 'COMMERCIAL',
        pointPerCard: 1,
        from: 'neighbors',
      },
    ],
  },
  {
    id: 'philosophers_guild',
    name: 'Philosophers Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [
      {
        type: 'resource',
        resources: ['CLAY', 'CLAY', 'CLAY', 'TEXTILE', 'PAPER'],
      },
    ],
    provides: [
      {
        type: 'point-per-card',
        perCardType: 'SCIENTIFIC',
        pointPerCard: 1,
        from: 'neighbors',
      },
    ],
  },
  {
    id: 'magistrates_guild',
    name: 'Magistrates Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [
      {
        type: 'resource',
        resources: ['WOOD', 'WOOD', 'WOOD', 'STONE', 'TEXTILE'],
      },
    ],
    provides: [
      {
        type: 'point-per-card',
        perCardType: 'CIVILIAN',
        pointPerCard: 1,
        from: 'neighbors',
      },
    ],
  },
  {
    id: 'spies_guild',
    name: 'Spies Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [
      {
        type: 'resource',
        resources: ['CLAY', 'CLAY', 'CLAY', 'GLASS'],
      },
    ],
    provides: [
      {
        type: 'point-per-card',
        perCardType: 'MILITARY',
        pointPerCard: 1,
        from: 'neighbors',
      },
    ],
  },
  {
    id: 'strategists_guild',
    name: 'Strategists Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [
      {
        type: 'resource',
        resources: ['ORE', 'ORE', 'STONE', 'TEXTILE'],
      },
    ],
    provides: [
      {
        type: 'points-per-military-token',
        tokenType: 'defeat',
        pointsPerToken: 1,
        from: 'neighbors',
      },
    ],
  },
  {
    id: 'builders_guild',
    name: 'Builders Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [
      {
        type: 'resource',
        resources: ['STONE', 'STONE', 'CLAY', 'CLAY', 'GLASS'],
      },
    ],
    provides: [
      {
        type: 'point-per-card',
        perCardType: 'WONDER',
        pointPerCard: 1,
        from: 'both',
      },
    ],
  },
  {
    id: 'scientists_guild',
    name: 'Scientists Guild',
    age: 3,
    type: 'GUILD',
    minPlayers: 3,
    cost: [
      {
        type: 'resource',
        resources: ['WOOD', 'WOOD', 'ORE', 'ORE', 'PAPER'],
      },
    ],
    provides: [
      {
        type: 'science-choice',
        symbols: ['COMPASS', 'GEAR', 'TABLET'],
      },
    ],
  },
];
